name: Gitleaks Scan and DefectDojo Integration

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (adjust as needed)
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Gitleaks
      run: |
        curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v8.0.1/gitleaks-linux-amd64 -o gitleaks
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/gitleaks

    - name: Run Gitleaks Scan
      run: |
        gitleaks detect --repo-path . --json --redact > gitleaks_report.json
      continue-on-error: true  # Continue even if leaks are found (for demo purposes)

    - name: Upload Gitleaks findings to DefectDojo
      env:
        DO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
        DO_URL: ${{ secrets.DEFECTDOJO_URL }}
        PRODUCT_ID: ${{ secrets.DEFECTDOJO_PRODUCT_ID }}
      run: |
        curl -X POST $DO_URL/api/v2/import-scan/ \
        -H "Authorization: Token $DO_API_KEY" \
        -H "Content-Type: application/json" \
        -F "file=@gitleaks_report.json" \
        -F "product=$PRODUCT_ID" \
        -F "engagement=$PRODUCT_ID"
